services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kasir-app
    container_name: kasir-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - kasir-network
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: kasir-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - kasir-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: kasir-db
    restart: unless-stopped
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_DATABASE: kasir_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: kasir_password
      MYSQL_USER: kasir_user
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3307:3306"
    networks:
      - kasir-network

  # --- BLOK BARU YANG DITAMBAHKAN ---
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: kasir-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=root_password
    networks:
      - kasir-network
    depends_on:
      - db
  # ------------------------------------

networks:
  kasir-network:
    driver: bridge

volumes:
  dbdata:
    driver: local